name: sesimiduy
description: A new Flutter project.
publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.19.1 <3.0.0"

dependencies:
  cloud_firestore: ^4.4.2
  cupertino_icons: ^1.0.2
  dash_flags: ^0.0.3
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  firebase_core: ^2.6.1
  flutter:
    sdk: flutter
  flutter_custom_clippers: ^2.1.0
  flutter_riverpod: ^2.1.3
  flutter_tagging_plus: ^4.0.1
  font_awesome_flutter: ^10.3.0
  geolocator: ^9.0.2
  google_maps_flutter: ^2.2.3
  google_maps_flutter_web: ^0.4.0+5
  json_annotation: ^4.8.0
  kartal: ^2.8.0
  logger: ^1.1.0
  responsive_builder: ^0.5.1
  responsive_framework: ^0.2.0
  syncfusion_flutter_pdfviewer: ^20.4.49
  textfield_tags: ^2.0.2
  webview_flutter: ^4.0.2

flutter_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app/app_icon.jpg"

dev_dependencies:
  build_runner: ^2.3.3
  flutter_gen_runner: ^5.2.0
  flutter_test:
    sdk: flutter

  json_serializable: ^6.6.1
  very_good_analysis: ^4.0.0+1
  flutter_launcher_icons: ^0.10.0

flutter_gen:
  output: lib/product/generated/

flutter:
  uses-material-design: true

  assets:
    - assets/translations/
    - assets/icons/
    - assets/docs/
    - assets/bundle/
